### ISSUE TITLE
好像没用？？？

### ISSUE THREAD

**Issue by Krysaya** [shixueqian/PrintBeautifulLog#1]
![image](https://user-images.githubusercontent.com/18435485/49909480-1e44d600-feba-11e8-94c1-018abe3dd601.png)
文件夹下也没有说明上那两个文件？？？
![wechatimg3](https://user-images.githubusercontent.com/18435485/49909496-34eb2d00-feba-11e8-969a-6b04bee5165c.jpg)

**Comment by Krysaya** [comment]
拖进工程重新编译也不行，，没啥反映，不起作用

**Comment by shixueqian** [comment]
已经更新说明了。
直接将 SQPrintJsonLog.m 拉入到工程中即可自动生效使用。
不生效的原因应该是您的工程使用了Release模式，代码里面限制了只在Debug模式使用的，如果想要在Release模式也生效，可以直接修改下文件，将限制去掉。
