### ISSUE TITLE
请求 cocoapods 集成支持

### ISSUE THREAD

**Issue by Navimark** [shixueqian/PrintBeautifulLog#3]
希望通过类似`pod 'rintBeautifulLog', :configurations => ['Debug']`的方式引入代码，好处：
- 对工程侵入性降低，管理更方便
- 可以将代码隔离在 `Debug`环境中，避免`Release`中引入非必要的代码
- 方便版本控制

**Comment by shixueqian** [comment]
已支持cocoapods引入
